export const Main = () => {
  return (
    <div className="flex">
      <div className="max-w-[300px] w-full min-h-[100vh] flex flex-col gap-7  bg-[#4a194e]">
        <div className="mt-8 pl-5 flex flex-col gap-4">
          <div className="hover:cursor-pointer text-white font-semibold flex flex-col gap-1">
            <div className="flex gap-2">
              <span className="underline">Plants shop</span>
              <div>{">"}</div>
            </div>

            <div className="ml-5 mt-3 flex flex-col gap-2">
              <div className="underline">Test 1</div>
              <div>Test 2</div>
            </div>
          </div>
          <div className="hover:cursor-pointer text-white font-semibold ">
            Candy shop
          </div>
          <div className="hover:cursor-pointer text-white font-semibold ">
            BB franchise
          </div>
        </div>
      </div>

      <div className="p-9 flex flex-col gap-7">
        <div className="flex flex-col gap-4 border border-solid p-4 rounded-lg">
          <div>
            <span>
              <span className="font-bold">From:</span> Ivan Popovych (customer)
            </span>
          </div>
          <div>
            <span>
              <span className="font-bold">Email:</span> ipopovych2004@gmail.com
            </span>
          </div>
          <span>
            <span className="font-bold">Message:</span> Can you recommend me an
            interesting plant for the room that is available in your store?
          </span>
        </div>

        <div className="flex flex-col gap-4 border border-solid p-4 rounded-lg">
          <span>
            <span className="font-bold">Response:</span> Autogenerated
          </span>
          <span>
            <span className="font-bold">Message: </span>
            Thank you for reaching out! At Hello Plants, we have a fantastic
            selection of indoor plants that can truly enhance your space. One of
            our top recommendations is the **Snake Plant**. It's not only
            visually striking with its tall, upright leaves, but it's also
            incredibly low-maintenance and purifies the air, making it perfect
            for any room. If you're looking for something a bit more colorful,
            consider the **Pothos**. Its trailing vines and heart-shaped leaves
            can add a lovely touch to shelves or hanging planters. We would be
            happy to help you choose the perfect plant for your room! Feel free
            to reach us with any specific preferences or questions you might
            have, and we’ll guide you through our options. Happy planting!
          </span>
        </div>
      </div>
    </div>
  );
};
